# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
    push:
        branches: [master]

jobs:

    # Code Stage (with Shift left)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # Secret Scanning
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    # Dependency Checks
    dependency-checks:
        uses: ./.github/workflows/dependancy-scan.yml

    # Docker Checks
    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit
    # SonarQube Checks
    sonar-scans:
        uses: ./.github/workflows/sonar-scans.yml
        secrets: inherit

    # code tests
    code-tests:
        uses: ./.github/workflows/code-tests.yml
        secrets: inherit
    # Docker Push
    docker-push:
        needs: [code-quality, secret-scanning, dependency-checks, docker-checks, sonar-scans, code-tests]
        uses: ./.github/workflows/docker-push.yml